spring:
  application:
    name: bank-application
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082  

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
       

server:
  port: 8443
  
  # Configure SSL
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: "$2a$12$V/vMHom7B71tk7WFU2k1l.p.iNMmIVVP/nS.5xktfI4kJLNrmsJvy"
#    key-store-type: PKCS12
#    key-alias: mykey

        
  
