spring:
  application:
    name: bank-application
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082  

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
        
  
